### ISSUE TITLE
Add support for Right To Left languages

### ISSUE THREAD

**Issue by goldenson** [Shopify/pseudolocalization#18]
## Add support for `Right-2-Left` language (RTL) 

Is it even possible from the backend? 🤔 
Yes with [UBA algorithm](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics)

https://useyourloaf.com/blog/natural-text-alignment-for-rtl-languages/

**Comment by christianblais** [comment]
I'm not sure how this impacts pseudolocalization? Given a string of text, the input is scrambled, but it has nothing to do with whether or not that text was rtl or ltr. Or maybe I'm missing something?

**Comment by goldenson** [comment]
Yep I've been thinking at this recently and I agree with you it does not seem to affect pseudolocalization directly.

The more I think about pseudolocaliztion the more I believe we would need something displayed in the UI to toggle different language (pseudolocalization included) and more features.

---

From my research, an HTML property allows us to force the browser to render the text from Right to Left using the Unicode Bidirectional Algorithm described [here](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics). And some [best practices](https://www.w3.org/International/tutorials/bidi-xhtml/) to create HTML Pages in Arabic, Hebrew and Other Right-to-left Scripts.


>IN A NUTSHELL
Add a dir attribute to the html tag to set the default base direction of your page if it is right-to-left. Use the dir attribute on block elements within the page only where you need to change the base direction.

>For inline text, tightly wrap all opposite-direction phrases in markup that sets their base direction.

>Use dir=auto to automatically set the base direction of form fields, pre elements or text inserted into the page. Use the dirname attribute if you need to pass information about the base direction of form input to the server.

>Avoid using CSS or Unicode control codes for managing direction where you can use markup.

>Use logical ordering of bidirectional text, rather than visual ordering, and let the Unicode Bidirectional Algorithm take the strain.
